config/routes.rb
Rails.application.routes.draw do
  resources :pins

  devise_for :users
  root "pins#index"
  get "about" => "pages#about" # Creates about_path
  get "winelist" => "pages#winelist" # Creates Wine_List_Path
  get "sommelier" => "pages#sommelier" # Creates Sommelier_Corner_Path

end

app/models/pin.rb
class Pin < ActiveRecord::Base
	belongs_to :user	

	has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }

	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

	validates :image, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


  has_many :pins, dependent: :destroy   

  validates :name, presence: true    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 # Prevent CSRF attacks by raising an exception.
 # For APIs, you may want to use :null_session instead.
 protect_from_forgery with: :exception
 before_filter :configure_permitted_parameters, if: :devise_controller?

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home  	
  end

  def winelist
  end

  def sommelier
  end

  def about  	
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page => 15)
  end 
  def show
  end

  def new
    @pin = current_user.pins.build
  end

  def edit
  end

  def create
    @pin = current_user.pins.build(pin_params)
    if @pin.save
      redirect_to @pin, notice: 'Pin was successfully created.'
    else
      render action: 'new'
    end
  end

  def update
    if @pin.update(pin_params)
      redirect_to @pin, notice: 'Pin was successfully updated.'
    else
      render action: 'edit'
    end
  end

  def destroy
    @pin.destroy
    redirect_to pins_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
      @pin = current_user.pins.find_by(id: params[:id])
      redirect_to pins_path, notice: "Not authorized to edit this pin" if @pin.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Las Vegas Wine & Spirits", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Top 10", winelist_path %></li>
        <li><%= link_to "Sommelier Corner", sommelier_path %></li>
        <li><%= link_to "About", about_path %></li>
          <% if user_signed_in? %>
            <li>
            <%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> New Pin
            <% end %>
          </li>
        <li><%= link_to "Account Settings", edit_user_registration_path %>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
          <% else %>  
        <li><%= link_to "Sign In", new_user_session_path %></li>  
        <% end %>  
                </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Las Vegas Wine & Dine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>

	<%= render 'layouts/header' %>
	<div class="container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, msg, class: "alert alert-info") %>
		<% end%>
		<%= yield %>
	</div>

</body>
</html>

app/views/pages/_home.html.erb
<div class="jumbotron center">
<h1>Welcome Wine Lovers!</h1>

<% if user_signed_in? %>

<% else %>	
<p>
	<%= link_to "Log in", new_user_session_path, class: "btn btn-success btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>

<iframe src="https://player.vimeo.com/video/99491624?title=0&byline=0&portrait=0" width="275" height="155" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe><p>To the city that NEVER sleeps!</p>

<% end %>

<h3>Enjoy your stay!</h3>

<h6>Provided by Dustin D. Rath ©2015</h6>


</div>

app/views/pages/about.html.erb
<div class="jumbotron center">
<h1>About Me</h1>
<p>Hello! My name is Dustin Rath. My wife, Boseon Rath, has been working within the food and beverage industry for several years. She made a comment to me some time ago, "huny, it sure would be nice to have a place to easily share my ideas with other wine lovers on the fly!" I took that comment and decided to put pen to paper.  I have to agree with her, after doing some research, I realized that it would be nice for individuals in the F&B world to have easy access to an online resource where they may share quick pictures and comments for review after their shift! Not only can this lead to paperless note taking, but also the diversification of ideas from others! Imagine a guest whom decides to visit your restaurant, we see it all the time, they take out their phones and snap a quick picture of their meal!  If you spot this on the job, why not take a picture of that entree, along with the drink selection they chose for their meal.  This could lead to stronger menu structuring! I hope you find this application to be entertaining and helpful in your career! If you have any suggestions please feel free to drop me an email - rathd@unlv.nevada.edu  </p>

<a href="http://s707.photobucket.com/user/Riiaa007/media/7f6ebc5c-d13d-4e96-b384-31e1be62ad5a.png.html" target="_blank"><img src="http://i707.photobucket.com/albums/ww80/Riiaa007/7f6ebc5c-d13d-4e96-b384-31e1be62ad5a.png" border="0" alt=" photo 7f6ebc5c-d13d-4e96-b384-31e1be62ad5a.png"/></a>

</div>

app/views/pages/home.html.erb
<div class="jumbotron center">
<h1>Welcome Wine Lovers!</h1>

<% if user_signed_in? %>

<iframe src="https://player.vimeo.com/video/116268602?title=0&byline=0&portrait=0" width="275" height="155" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p>Rock in Rio Las Vegas 2015! - Beer vs Wine</p>

<% else %>	
<p>
	<%= link_to "Log in", new_user_session_path, class: "btn btn-success btn-lg" %>
  <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</p>

<iframe src="https://player.vimeo.com/video/99491624?autoplay=1&title=0&byline=0&portrait=0" width="275" height="155" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe> <p>To the city that NEVER sleeps!</p>

<% end %>

<h3>Enjoy your stay!</h3>

<h6>Provided by Dustin D. Rath ©2015</h6>


</div>

app/views/pages/sommelier.html.erb
<div class="jumbotron center">
<h1>Sommelier Corner</h1>
<p>This area will consist of the most frequently paired options that leading sommeliers have voted on!</p>

<h4>Ask Chef Tony!</h4>
<iframe width="560" height="315" src="https://www.youtube.com/embed/5a_qIUzKrB8" frameborder="0" allowfullscreen></iframe>

<h4>Industry Thoughts!</h4>
<iframe width="560" height="315" src="https://www.youtube.com/embed/-Ym7_q1f4rI" frameborder="0" allowfullscreen></iframe>

<h4>Ary of Manliness!</h4>
<iframe width="560" height="315" src="https://www.youtube.com/embed/_DDL3seMRwo" frameborder="0" allowfullscreen></iframe>

</div>

app/views/pages/winelist.html.erb
<div class="jumbotron center">
<h1>2015 Top 10 Wine List Las Vegas!</h1>
<p>Below you will find a nice selection of locations in and around the Las Vegas, Nevada region that host a wonderful selection of fine wines and entrées! Please share your experience by posting images here at lasvegas-wine.com!</p>

<h4>Alizé at the Top of the Palms</h4>
<img src="http://www.gayot.com/images/reviews/alize.jpg" alt="Dining Room at Alizé at the Top of the Palms, Las Vegas, NV" title="Dining Room at Alizé at the Top of the Palms, Las Vegas, NV" style="padding: 3px;" border="0">
<p>Palms Casino Resort
4321 W. Flamingo Rd.
Las Vegas, NV	89103</p>

<h4>Aureole</h4>
<img src="http://farm3.static.flickr.com/2478/3818881392_da5672b357.jpg" alt="Looking into the Bar Room" width="500" height="333">
<p>Mandalay Bay Resort & Casino
3950 Las Vegas Blvd. S.
Las Vegas, NV	89119</p>

<h4>BARDOT Brasserie</h4>
<img src="http://www.gayot.com/images/reviews/bardot-brasserie.jpg" alt="Dining Room at BARDOT Brasserie, Las Vegas, NV" title="Dining Room at BARDOT Brasserie, Las Vegas, NV" style="padding: 3px;" border="0">
<p>CityCenter
Aria Resort & Casino
3730 Las Vegas Blvd. S.
Las Vegas, NV	89109</p>

<h4>Delmonico Steakhouse</h4>
<img src="http://www.gayot.com/images/reviews/delmonico-steakhouse.jpg" alt="Dining Room at Delmonico Steakhouse, Las Vegas, NV" title="Dining Room at Delmonico Steakhouse, Las Vegas, NV" style="padding: 3px;" border="0">
<p>The Venetian
3355 Las Vegas Blvd. S.
Las Vegas, NV	89109</p>

<h4>Joël Robuchon Restaurant</h4>
<img src="http://www.gayot.com/images/reviews/joel-robuchon.jpg" alt="Dining Room at Joël Robuchon Restaurant, Las Vegas, NV" title="Dining Room at Joël Robuchon Restaurant, Las Vegas, NV" style="padding: 3px;" border="0">
<p>MGM Grand Hotel & Casino
3799 Las Vegas Blvd. S.
Las Vegas, NV	89109</p>

<h4>Marché Bacchus</h4>
<img src="http://www.gayot.com/images/reviews/marche-bacchus.jpg" alt="Dining Room at Marché Bacchus, Las Vegas, NV" title="Dining Room at Marché Bacchus, Las Vegas, NV" style="padding: 3px;" border="0">
<p>Lakeside Center
2620 Regatta Dr., Ste. 106
Las Vegas, NV	89128</p>

<h4>Picasso</h4>
<img src="http://www.gayot.com/images/reviews/picasso.jpg" alt="Dining Room at Picasso, Las Vegas, NV" title="Dining Room at Picasso, Las Vegas, NV" style="padding: 3px;" border="0">
<p>Bellagio
3600 Las Vegas Blvd. S.
Las Vegas, NV	89109</p>

<h4>Portofino</h4>
<img src="http://www.gayot.com/images/reviews/portofino.jpg" alt="Dining Room at Portofino, Las Vegas, NV" title="Dining Room at Portofino, Las Vegas, NV" style="padding: 3px;" border="0">
<p>The Mirage
3400 Las Vegas Blvd. S.
Las Vegas, NV	89109</p>

<h4>Restaurant Guy Savoy</h4>
<img src="http://www.gayot.com/images/reviews/guy-savoy.jpg" alt="Dining Room at Restaurant Guy Savoy, Las Vegas, NV" title="Dining Room at Restaurant Guy Savoy, Las Vegas, NV" style="padding: 3px;" border="0">
<p>Augustus Tower
Caesars Palace
3570 Las Vegas Blvd. S.
Las Vegas, NV	89109</p>

<h4>Restaurant Guy Savoy</h4>
<img src="http://www.gayot.com/images/reviews/scarpetta-vegas.jpg" alt="Dining Room at Scarpetta, Las Vegas, NV" title="Dining Room at Scarpetta, Las Vegas, NV" style="padding: 3px;" border="0">
<p>The Cosmopolitan of Las Vegas
3708 Las Vegas Blvd. S.
Las Vegas, NV	89109</p>

</div>

app/views/pins/_form.html.erb
<%= form_for @pin, html: { multipart: true } do |f| %>
  <% if @pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% @pin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :image %><br>
    <%= f.file_field :image, class: "form-control"  %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control"  %>
  </div>
  
    <div class="form-group">
    <%= f.submit class: "btn btn-primary"%>
  </div>
<% end %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<div id="pins" class="transitions-enabled">
  <% @pins.each do |pin| %>
    <div class="box panel panel-default">
      <%= link_to image_tag(pin.image.url(:medium)), pin %>
      <div class="panel-body">
        <%= pin.description %><br/>
        <strong><%= pin.user.name if pin.user %></strong>
        
        <% if current_user && (pin.user == current_user) %>
          <div class="actions">
            <%= link_to edit_pin_path(pin) do %>
              <span class="glyphicon glyphicon-edit"></span>
              Edit
            <% end %>
            <%= link_to pin, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <span class="glyphicon glyphicon-trash"></span>
              Delete
            <% end %>
          </div>
        <% end %>

      </div>
    </div>
  <% end %>
</div>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<%= link_to 'Back', pins_path %>

<div class="row">
  <div class="col-md-offset-2 col-md-8">
    <div class="panel panel-default">
      <div class="panel-heading center">
        <%= image_tag @pin.image.url(:medium) %>
      </div>
      <div class="panel-body">
        <p><%= @pin.description %></p>
        <p><strong><%= @pin.user.name if @pin.user %></strong></p>

        <% if @pin.user == current_user %>
         <%= link_to edit_pin_path(@pin) do %>
        <i class="fa fa-pencil"></i>
        Edit
      <% end %>
        <% end %>

      </div>
    </div>
  </div>
</div>